version: '3'

services:
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:


curl --request POST \
--url http://66.42.44.52:9001/ \
--header 'Cache-Control: no-cache' \
--header 'Content-Type: application/json' \
--data '{"codigo":"12345","nome":"Weslley","email":"weslleycsil@email.com"}'